import type { MetadataRoute } from 'next';

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: '無限ProtoPedia',
    short_name: '無限PP',
    description:
      '仕事中のおさぼりから酒宴のつまみにも、寝酒のお供に、気付けば夜更け、朝ぼらけ',
    id: '/',
    start_url: '/',
    // lang: 'ja-JP',
    // dir: 'ltr',
    display: 'standalone',
    orientation: 'any',
    display_override: ['window-controls-overlay', 'standalone'],
    background_color: '#000000',
    theme_color: '#000000',
    scope: '/',
    categories: ['entertainment', 'productivity'],
    launch_handler: {
      client_mode: 'focus-existing',
    },
    // Generated by `npm run generate-pwa-assets` (@vite-pwa/assets-generator,
    // minimal-2023 preset). Keep these in sync with the generated files in
    // `public/icons/`.
    icons: [
      {
        src: '/icons/pwa-64x64.png',
        sizes: '64x64',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/pwa-192x192.png',
        sizes: '192x192',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/pwa-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: '/icons/maskable-icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    // Add screenshots to enable Richer PWA Install UI on desktop and mobile
    // Ref: https://developer.chrome.com/docs/web-platform/web-app-install-banners/#add-screenshots
    screenshots: [
      // Mobile (narrow) screenshot
      {
        src: '/screenshots/ss-mobile-dark.png',
        sizes: '780x1682',
        type: 'image/png',
        form_factor: 'narrow',
        label: 'Random prototype list on mobile (dark mode)',
      },
      // Desktop wide screenshot (light mode)
      {
        src: '/screenshots/ss-fhd-light.png',
        sizes: '2300x1294',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Prototype dashboard on desktop (light mode)',
      },
      // Additional wide screenshot (dark mode)
      {
        src: '/screenshots/ss-4k-dark.png',
        sizes: '2300x1294',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Prototype dashboard on desktop (dark mode)',
      },
    ],
  };
}
